### ISSUE TITLE
Installation instructions should mention the need to install Cheetah

### ISSUE THREAD

**Issue by svenaas** [chleggett/homebrew-gqrx#12]
Thank you for creating and maintaining this repo. I'm installing on El Capital (10.11.2) and when I reached the `brew install gqrx` step I got this:

```
$ brew install gqrx
==> Installing gqrx from chleggett/gqrx
gr-osmosdr: Unsatisfied dependency: Cheetah
Homebrew does not provide Python dependencies; install with:
  pip install Cheetah
Error: An unsatisfied requirement failed this build.
```

Running `pip install Cheetah` as suggested seems to have worked fine, but you should probably mention it in the installation instructions. 

Thanks again, and happy new year!

**Comment by chleggett** [comment]
This is the expected behavior. It is the way that Homebrew requires handling Python modules.

To get past this, run:

    $ brew install python
    $ pip install Cheetah
