### ISSUE TITLE
Unable to build on 10.10.2

### ISSUE THREAD

**Issue by inktomi** [chleggett/homebrew-gqrx#5]
I just installed all the dependencies as listed in the readme, and get the following error at the end:

==> Installing gqrx from chleggett/homebrew-gqrx
==> Installing gqrx dependency: gr-osmosdr
==> Downloading http://cgit.osmocom.org/gr-osmosdr/snapshot/gr-osmosdr-0.1.4.tar.gz
######################################################################## 100.0%
==> cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/gr-osmosdr/0.1.4 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAME
==> make install
/usr/local/Library/ENV/4.3/clang++   -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 0.1.4 -o libgnuradio-osmosdr.0.1.4.dylib -install_name /tmp/gr-osmosdr-MtJjXT/gr-osmosdr-0.1.4/build/lib/libgnuradio-osmosdr.0.1.4.dylib CMakeFiles/gnuradio-osmosdr.dir/source_impl.cc.o CMakeFiles/gnuradio-osmosdr.dir/sink_impl.cc.o CMakeFiles/gnuradio-osmosdr.dir/ranges.cc.o CMakeFiles/gnuradio-osmosdr.dir/device.cc.o CMakeFiles/gnuradio-osmosdr.dir/fcd/fcd_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/file/file_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/rtl/rtl_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/rtl_tcp/rtl_tcp_source_f.cc.o CMakeFiles/gnuradio-osmosdr.dir/rtl_tcp/rtl_tcp_source_c.cc.o CMakeFiles/gnuradio-osmosdr.dir/rfspace/rfspace_source_c.cc.o /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libgnuradio-runtime.dylib /usr/local/lib/libgnuradio-blocks.dylib /usr/local/lib/libgnuradio-pmt.dylib /usr/local/lib/libgnuradio-fcd.dylib /usr/local/lib/librtlsdr.dylib 
cd /tmp/gr-osmosdr-MtJjXT/gr-osmosdr-0.1.4/build/lib && /usr/local/Cellar/cmake/3.1.2/bin/cmake -E cmake_symlink_library libgnuradio-osmosdr.0.1.4.dylib libgnuradio-osmosdr.0.1.4.dylib libgnuradio-osmosdr.dylib
/usr/local/Cellar/cmake/3.1.2/bin/cmake -E cmake_progress_report /tmp/gr-osmosdr-MtJjXT/gr-osmosdr-0.1.4/build/CMakeFiles  3 4 5 6 7 8 9 10 11 12
[ 81%] Built target gnuradio-osmosdr
make: *** [all] Error 2

**Comment by inktomi** [comment]
Here are the verbose logs..

https://gist.github.com/inktomi/44a3e57aa2aff077cd04

**Comment by chleggett** [comment]
Thanks for this. I'll have a look as soon as I get a chance.

**Comment by inktomi** [comment]
I tracked it down to needing to use head versions of gr-osmosdr and related dependencies via https://github.com/titanous/homebrew-gnuradio, but then once I was able to build finally the binary was quite unstable so I think there are some inconsistencies still.

**Comment by floehopper** [comment]
@inktomi, @chleggett: I'm seeing this problem too. Have either of you got any further? Thanks.

**Comment by floehopper** [comment]
@inktomi: In case it helps, I seem to have fixed my problem by installing the cheetah python package using `pip install cheetah` before then running `brew install gqrx`. I notice that you have the [same error in your log file](https://gist.github.com/inktomi/44a3e57aa2aff077cd04#file-gistfile1-txt-L261) that made me try installing cheetah, so it might help you too.

**Comment by inktomi** [comment]
Hi - 

I tried that on a fresh laptop (since I'm at work), but it seems that the current gnuradio doesn't build. 

https://gist.github.com/inktomi/10c2de8509356e932245

I also entered that on the gnuradio issues here 
https://github.com/metacollin/homebrew-gnuradio/issues/24

**Comment by jmegawarne** [comment]
I got this working by doing `sudo pip install Cheetah`, as I tried to manually compile gr-osmosdr and found that Python module was missing.

**Comment by inktomi** [comment]
Unfortunately that doesn't seem to fix it for me:

https://gist.github.com/inktomi/e887ae4c7292a423e573

**Comment by RyanScottLewis** [comment]
`sudo pip install cheetah` then `brew install gqrx` Worked for me as well.

**Comment by chleggett** [comment]
Sorry, I've been away for a while, but I am looking into this now.

@inktomi will you please try to compile again on 10.10.3 and let me know if you are still seeing the issue.

**Comment by chleggett** [comment]
@inktomi I looked into it a little more. You had different issues on the two machines that you tried:

1) A build error with the gr-osmosdr package that I maintain
2) A build error with gnuradio--matplotlib

I am looking into the first one.

On the second one, I am not sure that is coming from the package that @metacollin maintains.

Will you please run "brew info gnuradio" and post the results.

It should look like this:

cleggett@xelda ~ % brew info gnuradio                                                                                                                         
gnuradio: stable 3.7.5.1, HEAD
http://gnuradio.org
/usr/local/Cellar/gnuradio/3.7.5.1 (4333 files, 130M)
  Built from source
From: https://github.com/metacollin/homebrew-gnuradio/blob/master/gnuradio.rb
==> Dependencies
Build: cmake ✔, swig ✔
Required: boost ✔, cppunit ✔, gsl ✔, fftw ✔, pygtk ✔, sdl ✔, libusb ✔, orc ✔, pyqt ✔, pyqwt ✔, sphinx ✔, wxpython ✔, wxmac ✔, freetype ✔
==> Options
--with-brewed-python
	Use the Homebrew version of Python
--without-docs
	Build gnuradio documentation
--without-qt
	Build with QT widgets in addition to wxWidgets
--HEAD
	Install HEAD version

**Comment by inktomi** [comment]
Hi -

I apologize for the delay. I'm in the middle of moving.
------

$ brew info gnuradio

gnuradio: stable 3.7.5.1, HEAD

http://gnuradio.org

/usr/local/Cellar/gnuradio/3.7.5.1 (7100 files, 249M) *

  Built from source

From:
https://github.com/metacollin/homebrew-gnuradio/blob/master/gnuradio.rb

*==>** Dependencies*

Build: cmake *✔*, swig *✔*

Required: boost *✔*, cppunit *✔*, gsl *✔*, fftw *✔*, pygtk *✔*, sdl *✔*,
libusb *✔*, orc *✔*, pyqt *✔*, pyqwt *✔*, sphinx *✔*, wxpython *✔*, wxmac
*✔*, freetype *✔*

*==>** Options*

--with-brewed-python

Use the Homebrew version of Python

--without-docs

Build gnuradio documentation

--without-qt

Build with QT widgets in addition to wxWidgets

--HEAD

Install HEAD version

**Comment by mark-leone** [comment]
I've done what was suggested here, installed librtlsdr from HEAD and installed cheetah. Still when I install gqrx it fails because it doesn't find gruel. I searched al over and tried many things, bit I don't know how 'm supposed to satisfy the gruel dependency.

**Comment by chleggett** [comment]
I am going to close this issue although it may still be unresolved for you guys because I am changing my gnuradio dependency recommendation away from metacollin's formula and to the new "official" one in the Homebrew repository. This will of course change a bunch of "stuff" and may fix or break the install in new ways.
