### ISSUE TITLE
Compile error in 10.8.5

### ISSUE THREAD

**Issue by woo2** [chleggett/homebrew-gqrx#7]
Hi,
I'm trying to install gnuradio but I'm having some issues. `brew doctor` fails with the following:

    Error: compile error
    /usr/local/Library/Taps/metacollin/homebrew-gnuradio/gnuradio.rb:115: syntax error, unexpected    tSTAR, expecting tAMPER
    system "cmake", "..", *args, *std_cmake_args
                                    ^
    Please report this bug:
    https://git.io/brew-troubleshooting
 
    /usr/local/Library/Taps/metacollin/homebrew-gnuradio/gnuradio.rb:124:in `load_file'
    /usr/local/Library/Homebrew/formulary.rb:82:in `klass'
    /usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
    /usr/local/Library/Homebrew/formulary.rb:200:in `factory'
    /usr/local/Library/Homebrew/formula.rb:604:in `each'
    /usr/local/Library/Homebrew/formula.rb:602:in `each'
    /usr/local/Library/Homebrew/cmd/doctor.rb:931:in `check_for_linked_keg_only_brews'
    /usr/local/Library/Homebrew/cmd/doctor.rb:1256:in `send'
    /usr/local/Library/Homebrew/cmd/doctor.rb:1256:in `doctor'
    /usr/local/Library/Homebrew/cmd/doctor.rb:1254:in `each'
    /usr/local/Library/Homebrew/cmd/doctor.rb:1254:in `doctor'
    /usr/local/Library/brew.rb:140:in `send'
    /usr/local/Library/brew.rb:140

`brew install gruradio` fails with the same problem.

I am running 10.8.5, Xcode 5.1.1, Build version 5B1008 (not current, I haven't had issues with anything else)

What should I do?

**Comment by chleggett** [comment]
The problems shown in this issue are outside of the scope of the Gqrx formula.

I'm not sure what's going on, but it looks like you are missing the command line tools for compiling.

Look to Homebrew documentation for answers.
