### ISSUE TITLE
Switch to new GnuRadio formula has been released in the Homebrew library?

### ISSUE THREAD

**Issue by chleggett** [chleggett/homebrew-gqrx#9]
Hey @metacollin, I just noticed that there is a GnuRadio formula in Homebrew's library.

Any idea if it works? Are there any advantages of sticking with yours, or can my gqrx formula switch over to that one now?

Let me know what you think.

**Comment by metacollin** [comment]
Yeah, I saw it. It doesn't work if you build with documentation, but I'm
about to do a pull request that should fix that.  I've not really had the
free time to properly maintain my tap, and beyond that, the formula in the
official repo has managed to do things without requiring any manual python
management, and more importantly, seems simply better written and more
thorough.  I noticed it existed a couple of weeks ago, but just now have
started looking into it.

And, as much as I regret it, I see no advantage, except perhaps reduced
build time (the formula must rebuild a large number of python dependencies
from scratch every time - but this is of little consequence given bottles
and the infrequency of gnuradio releases) to using my tap, and many
disadvantages, so I would recommend abandoning my tap as a dependency and
using the official formula.  Thanks for asking, but we both know the
official formula is much better, and that is what you should use :).

**Comment by metacollin** [comment]
I will be updating the read me of my tap to reflect that it is kept for historical purposes, but is deprecated and the official homebrew gnuradio formula is used.

Plus, I would suggest seeing about getting your gqrx tap included in the official repo as well - the only real barrier to this I think was its dependency on my tap, but now that is no longer necessary, and once its updated to work with the official formula, it ought to be happily accepted.  If you want, of course.

**Comment by metacollin** [comment]
Actually, I fixed the --with-documentation problem, but it doesn't build because it can't find wx, though I have it and wxpython installed through homebrew.  I'd be interested to hear if it builds for you.  I would think that a non-building formula would be caught by the homebrew buildbot and not make get pulled into the official repo, so I am leaning heavily towards it being some sort of thing I screwed up on my system rather than the formula.  I am also running El Capitan 10.11.1 which could be the issue.

**Comment by chleggett** [comment]
@metacollin thanks for all of your work and help.

I wouldn't have gotten the Gqrx formula to the point where it is without you.

I am going to change my gnuradio dependency recommendation to be the "official" gnuradio in the homebrew repo.

I also plan to submit the Gqrx formula itself for inclusion in the homebrew repo after I clean it up a tad bit more.

Thanks again.
